apiVersion: v1
kind: Pod
metadata:
  name: xpu-pod-1
spec:
  containers:
    - name: xpu-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
      resources:
        requests:
          demo.com/xpu: "1"
        limits:
          demo.com/xpu: "1"